### ISSUE TITLE
Issue #01 - Wiki Home Page

### ISSUE THREAD

**Issue by keginzburg** [joe-delaney/slack-chat#1]
# Wiki Home Page
- [X] Is the first page you see upon entering the wiki
- [X] Contains a welcome message
- [x] Contains a link/placeholder for a link to the live page
- [X] All links in the right sidebar should contain each wiki page and link to the correct page
- [X] Correctly formatted
  - [X] each wiki page is listed in bullet points
  - [X] all links route the correct page

## Comments
Looks great so far, I would just add some text indicating you plan on adding a live link under your welcome message.

**Comment by joe-delaney** [comment]
Great thanks, just added in the placeholder for the live link
