### ISSUE TITLE
Issue #07 - Splash/User Auth MVP

### ISSUE THREAD

**Issue by keginzburg** [joe-delaney/slack-chat#11]
Hey Joe,

Just a few small notes:

1. Not a big deal, but when I manually change the wildcard id for users in the users dashboard (https://slack--chat.herokuapp.com/#/user-dashboard/users/28), it seems like it could use some type of exception handling when the user doesn’t exist. Currently, it just displays an empty user dashboard. Not sure if this is the default behavior for Slack.

2. Also, when resizing the window (to a very small size) with the user-dashboard open, your Profile header has some interesting CSS interaction with the top bar of your Channel/Messages component. Let me know if you have trouble observing this.

Otherwise, these are negligible for the time being and I say you're good to move on to your next MVP. Please reply with a comment so I know you received this.

**Comment by joe-delaney** [comment]
Got it, yeah I will make a not of both of these things. For the first, I think slack redirects to an error page saying something went wrong, so I can work on that if I get some extra time towards the end and then I will play around with that CSS on the nav bar. Thanks for the feedback!
