### ISSUE TITLE
Issue #02 - MVP List

### ISSUE THREAD

**Issue by keginzburg** [joe-delaney/slack-chat#2]
# MVP List
- [X] Should have 7 MVPs.
  - [X] 3 of those are User Auth, Heroku, and Production README.
  - [X] The other 4 are from the [MVP List](https://github.com/appacademy/curriculum/blob/master/full-stack-project/proposal/mvp-list.md) or they have clarified them with you
- [X] Contains a description sentence of the app
- [X] Includes two to three detailed bullets on functionality and presentation of feature
- [X] At least one CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
- [X] Estimates how long it will take the code each MVP
- [X] Correctly formatted
  - [X] MVPs are listed in an ordered list
  - [X] Each MVP is broken down into bullet points

## Comments
You currently have your main MVPs scheduled for 9.5 days of work. You technically have 14 full days to work on this project. Do you think you need more time for your main 7 MVPs?

**Comment by joe-delaney** [comment]
Yeah, I think they may take longer. I added in some cushion to each of them to give me more time to make sure they are perfect before moving on.
