### ISSUE TITLE
Issue #03 - Schema

### ISSUE THREAD

**Issue by keginzburg** [joe-delaney/slack-chat#3]
# Database Schema
- [X] Contains correct datatypes
- [X] Contains appropriate constraints/details
  - [X] primary key
  - [X] not null
  - [X] unique
  - [X] indexed
  - [X] foreign key
- [X] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made
 - [X] foreign key and table name are lowercased, snake_cased and `back_ticked`
- [X] Correctly formatted
  - [X] schema is written in a table format
  - [X] the table’s name are lowercased, snake_cased and `back_ticked`
  - [X] the table header column names are bolded
  - [X] columns names are lowercased and snaked_cased and `back_ticked`

## Comments
The use of polymorphic associations here had me do a double-take initially, but looks pretty good.

1. Users
    1. For Associations, please use backticks to indicate the name of associations as well (created_channels, authored_messages). Should reflect in the rest of schema.
2. Messages
    1. Use of polymorphic associations is interesting for group or channel. At first, I wasn’t sure how you were including “DMs” here, but if your Group Table is flexible enough to handle “DMs” or “Group Messages”, then looks good.
3. Group
    1. Does a group have many users through subscriptions? If so, maybe update your association here?

**Comment by joe-delaney** [comment]
1. I have updated the formatting throughout the schema to reflect this comment.
2. I am envisioning the group table to be flexible to have "DMs" as well since a DM is effectively just a group message with only two members.
3. Yep,  good call, I just updated the schema to reflect this.

**Comment by keginzburg** [comment]
Sounds great!
