### ISSUE TITLE
Issue #05 - Backend Routes

### ISSUE THREAD

**Issue by keginzburg** [joe-delaney/slack-chat#5]
# Backend Routes
- [X] Contains the following sections: HTML, API Endpoints(Backend)
- [X] Each route has a description
- [X] API Endpoint routes contains wildcard variables written in `snake_case`
- [X] Routes does not contain [superfluous routes](https://github.com/appacademy/curriculum/blob/master/rails/readings/routing-part-ii.md)
- [X] Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
  + probably doesn’t need a `GET likes` api endpoint because that info comes through the post show

## Comments
Users

1. For the search feature route, do we need to append anything to our /api/users route? How are you going to search for users? Will you use a query string?

Channels

1. Same as above in reference to the Channel search feature.

Groups

1. How do you intend to implement the GET / - /api/groups/:id route?

**Comment by joe-delaney** [comment]
Yep good call, I agree with the query string approach for the search. I have updated the backend routes to reflect an optional query string for both the channels and the users. If the current user does not input anything for the query string, all channels and users will be returned.

For the groups id route, it should be a simple get request to the show route for groups. When a user selects the group index item from the left index view, this will trigger a fetchGroup api request with the appropriate group id.

**Comment by keginzburg** [comment]
Looks great!
