### ISSUE TITLE
Issue #06 - Frontend Routes & Components

### ISSUE THREAD

**Issue by keginzburg** [joe-delaney/slack-chat#6]
# Frontend Routes
- [X] Frontend routes contains wildcard variables written in `camelCase`
- [X] Correctly formatted
  - [X] Routes are displayed with `inline coding text` (backticks)

## Comments
This looks pretty solid to me. Only question is how you will handle new channels being created?

**Comment by joe-delaney** [comment]
I was thinking users would add a new channel or group through a modal, which wouldn't need a new frontend route. However, if I get into the weeds and a new route for the new channel makes more sense, I can always include that.

**Comment by keginzburg** [comment]
Gotcha, sounds good! I think you've got a solid set of design docs.
